from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class EventType(str, Enum):
    TASK_CREATED = "task_created"
    TASK_UNDERSTANDING = "task_understanding"
    TASK_PLANNING = "task_planning"
    PLAN_READY = "plan_ready"
    MODEL_SELECTED = "model_selected"
    MODEL_FALLBACK = "model_fallback"
    TASK_PROGRESS = "task_progress"
    AGENT_ACTIVITY = "agent_activity"
    TOOL_STARTED = "tool_started"
    TOOL_SELECTED = "tool_selected"
    TOOL_PERMISSION_CHECK = "tool_permission_check"
    TOOL_PROGRESS = "tool_progress"
    TOOL_COMPLETED = "tool_completed"
    TOOL_FAILED = "tool_failed"
    TOOL_RETRY = "tool_retry"
    BROWSER_OPENED = "browser_opened"
    BROWSER_ACTION = "browser_action"
    TERMINAL_STARTED = "terminal_started"
    TERMINAL_OUTPUT = "terminal_output"
    FILE_CHANGED = "file_changed"
    GIT_CHANGED = "git_changed"
    TEST_STARTED = "test_started"
    TEST_PASSED = "test_passed"
    TEST_FAILED = "test_failed"
    VERIFICATION_EVIDENCE = "verification_evidence"
    MCP_CONNECTED = "mcp_connected"
    MCP_TOOL_INVOKED = "mcp_tool_invoked"
    VISUALIZATION_REQUESTED = "visualization_requested"
    APPROVAL_REQUIRED = "approval_required"
    VERIFICATION_STARTED = "verification_started"
    VERIFICATION_PASSED = "verification_passed"
    VERIFICATION_FAILED = "verification_failed"
    TASK_COMPLETED = "task_completed"
    TASK_FAILED = "task_failed"
    TASK_CANCELLED = "task_cancelled"
    MEMORY_RETRIEVED = "memory_retrieved"
    MEMORY_CREATED = "memory_created"
    MEMORY_UPDATED = "memory_updated"
    MEMORY_SUPERSEDED = "memory_superseded"
    MEMORY_FORGOTTEN = "memory_forgotten"
    MEMORY_CONSOLIDATED = "memory_consolidated"
    SKILL_MATCHED = "skill_matched"
    SKILL_CREATED = "skill_created"
    SKILL_TESTING = "skill_testing"
    SKILL_STEP_STARTED = "skill_step_started"
    SKILL_PROMOTED = "skill_promoted"
    SKILL_FAILED = "skill_failed"
    SKILL_UPDATED = "skill_updated"
    AGENT_CREATED = "agent_created"
    AGENT_TESTING = "agent_testing"
    AGENT_READY = "agent_ready"
    AGENT_STARTED = "agent_started"
    AGENT_DELEGATED = "agent_delegated"
    AGENT_COMPLETED = "agent_completed"
    AGENT_PAUSED = "agent_paused"
    AGENT_FAILED = "agent_failed"
    LESSON_CREATED = "lesson_created"
    LEARNING_APPLIED = "learning_applied"
    INTEGRATION_CONNECTED = "integration_connected"
    INTEGRATION_DISCONNECTED = "integration_disconnected"
    INTEGRATION_ERROR = "integration_error"
    EMAIL_SEARCHED = "email_searched"
    EMAIL_READ = "email_read"
    EMAIL_DRAFTED = "email_drafted"
    EMAIL_SEND_APPROVAL_REQUIRED = "email_send_approval_required"
    EMAIL_SENT = "email_sent"
    EMAIL_VERIFIED = "email_verified"
    CONTACT_RESOLVED = "contact_resolved"
    CONTACT_AMBIGUOUS = "contact_ambiguous"
    CRM_UPDATED = "crm_updated"
    LEAD_RESEARCHED = "lead_researched"
    LEAD_QUALIFIED = "lead_qualified"
    OUTREACH_DRAFTED = "outreach_drafted"
    OUTREACH_APPROVAL_REQUIRED = "outreach_approval_required"
    OUTREACH_SENT = "outreach_sent"
    REPLY_DETECTED = "reply_detected"
    FOLLOWUP_SCHEDULED = "followup_scheduled"
    CALENDAR_READ = "calendar_read"
    AVAILABILITY_CHECKED = "availability_checked"
    MEETING_APPROVAL_REQUIRED = "meeting_approval_required"
    MEETING_CREATED = "meeting_created"
    MEETING_VERIFIED = "meeting_verified"
    BRIEFING_GENERATED = "briefing_generated"
    AUTOMATION_CREATED = "automation_created"
    AUTOMATION_SCHEDULED = "automation_scheduled"
    AUTOMATION_STARTED = "automation_started"
    AUTOMATION_PAUSED = "automation_paused"
    AUTOMATION_RESUMED = "automation_resumed"
    AUTOMATION_COMPLETED = "automation_completed"
    AUTOMATION_FAILED = "automation_failed"
    RESEARCH_STARTED = "research_started"
    RESEARCH_PLAN_READY = "research_plan_ready"
    SOURCE_DISCOVERED = "source_discovered"
    SOURCE_READ = "source_read"
    CLAIM_EXTRACTED = "claim_extracted"
    CONTRADICTION_FOUND = "contradiction_found"
    RESEARCH_VERIFIED = "research_verified"
    BROWSER_OBSERVED = "browser_observed"
    BROWSER_RECOVERED = "browser_recovered"
    CAPABILITY_GAP_DETECTED = "capability_gap_detected"
    API_DISCOVERED = "api_discovered"
    MCP_DISCOVERED = "mcp_discovered"
    SAAS_DISCOVERED = "saas_discovered"
    BOOKING_SEARCH_STARTED = "booking_search_started"
    BOOKING_OPTION_FOUND = "booking_option_found"
    BOOKING_APPROVAL_REQUIRED = "booking_approval_required"
    BOOKING_CONFIRMED = "booking_confirmed"
    ARTIFACT_STARTED = "artifact_started"
    ARTIFACT_RENDERED = "artifact_rendered"
    ARTIFACT_VALIDATION_FAILED = "artifact_validation_failed"
    ARTIFACT_VERIFIED = "artifact_verified"
    DELIVERY_PACKAGE_READY = "delivery_package_ready"
    DELIVERY_APPROVAL_REQUIRED = "delivery_approval_required"
    DELIVERY_SENT = "delivery_sent"
    DELIVERY_VERIFIED = "delivery_verified"
    DESKTOP_STARTUP_ENABLED = "desktop_startup_enabled"
    DESKTOP_STARTUP_DISABLED = "desktop_startup_disabled"
    APP_OPENED = "app_opened"
    APP_FOCUSED = "app_focused"
    APP_CLOSED = "app_closed"
    WINDOW_FOCUSED = "window_focused"
    WINDOW_MOVED = "window_moved"
    CLIPBOARD_READ = "clipboard_read"
    CLIPBOARD_WRITTEN = "clipboard_written"
    SCREEN_CAPTURED = "screen_captured"
    SCREEN_OBSERVED = "screen_observed"
    ACCESSIBILITY_ACTION = "accessibility_action"
    MOUSE_ACTION = "mouse_action"
    KEYBOARD_ACTION = "keyboard_action"
    DESKTOP_ACTION_VERIFIED = "desktop_action_verified"
    DESKTOP_ACTION_FAILED = "desktop_action_failed"
    DEVICE_CONNECTED = "device_connected"
    DEVICE_DISCONNECTED = "device_disconnected"
    DEVICE_COMMAND_STARTED = "device_command_started"
    DEVICE_COMMAND_COMPLETED = "device_command_completed"
    EMERGENCY_PAUSE = "emergency_pause"
    MARKET_DATA_REQUESTED = "market_data_requested"
    MARKET_DATA_RECEIVED = "market_data_received"
    MARKET_DATA_STALE = "market_data_stale"
    MARKET_RESEARCH_STARTED = "market_research_started"
    MARKET_THESIS_READY = "market_thesis_ready"
    TRADE_SETUP_CREATED = "trade_setup_created"
    TRADE_SETUP_REJECTED = "trade_setup_rejected"
    RISK_CHECK_STARTED = "risk_check_started"
    RISK_CHECK_PASSED = "risk_check_passed"
    RISK_CHECK_FAILED = "risk_check_failed"
    PAPER_ORDER_CREATED = "paper_order_created"
    PAPER_ORDER_FILLED = "paper_order_filled"
    PAPER_ORDER_CANCELLED = "paper_order_cancelled"
    PAPER_POSITION_OPENED = "paper_position_opened"
    PAPER_POSITION_CLOSED = "paper_position_closed"
    BACKTEST_STARTED = "backtest_started"
    BACKTEST_COMPLETED = "backtest_completed"
    BACKTEST_FAILED = "backtest_failed"
    STRATEGY_CREATED = "strategy_created"
    STRATEGY_VALIDATED = "strategy_validated"
    MARKET_ALERT_TRIGGERED = "market_alert_triggered"
    PAPER_TRADING_PAUSED = "paper_trading_paused"
    RISK_KILL_SWITCH_TRIGGERED = "risk_kill_switch_triggered"
    GOAL_CREATED = "goal_created"
    GOAL_UPDATED = "goal_updated"
    GOAL_COMPLETED = "goal_completed"
    GOAL_BLOCKED = "goal_blocked"
    HABIT_CREATED = "habit_created"
    HABIT_EVENT_RECORDED = "habit_event_recorded"
    HABIT_PATTERN_DETECTED = "habit_pattern_detected"
    HABIT_INSIGHT_CREATED = "habit_insight_created"
    ROUTINE_STARTED = "routine_started"
    ROUTINE_COMPLETED = "routine_completed"
    ROUTINE_MISSED = "routine_missed"
    FOCUS_STARTED = "focus_started"
    FOCUS_PAUSED = "focus_paused"
    FOCUS_COMPLETED = "focus_completed"
    COMMITMENT_CREATED = "commitment_created"
    COMMITMENT_DUE = "commitment_due"
    COMMITMENT_COMPLETED = "commitment_completed"
    DAILY_PLAN_CREATED = "daily_plan_created"
    PENDING_WORK_RECALLED = "pending_work_recalled"
    MORNING_BRIEFING_READY = "morning_briefing_ready"
    EVENING_REVIEW_READY = "evening_review_ready"
    WEEKLY_REVIEW_READY = "weekly_review_ready"
    PROACTIVE_SUGGESTION_CREATED = "proactive_suggestion_created"
    PROACTIVE_SUGGESTION_SUPPRESSED = "proactive_suggestion_suppressed"
    NOTIFICATION_BATCHED = "notification_batched"
    QUIET_MODE_STARTED = "quiet_mode_started"
    QUIET_MODE_ENDED = "quiet_mode_ended"
    # -- Phase 12: distributed multi-device runtime -----------------------
    NODE_REGISTERED = "node_registered"
    NODE_AUTHENTICATED = "node_authenticated"
    NODE_REVOKED = "node_revoked"
    NODE_ONLINE = "node_online"
    NODE_OFFLINE = "node_offline"
    TASK_DISPATCHED = "task_dispatched"
    TASK_HANDOFF_STARTED = "task_handoff_started"
    TASK_HANDOFF_COMPLETED = "task_handoff_completed"
    TASK_LEASE_EXPIRED = "task_lease_expired"
    SYNC_STARTED = "sync_started"
    SYNC_COMPLETED = "sync_completed"
    SYNC_CONFLICT = "sync_conflict"
    OFFLINE_COMMAND_QUEUED = "offline_command_queued"
    OFFLINE_COMMAND_EXPIRED = "offline_command_expired"
    BACKUP_STARTED = "backup_started"
    BACKUP_COMPLETED = "backup_completed"
    BACKUP_FAILED = "backup_failed"
    RESTORE_STARTED = "restore_started"
    RESTORE_COMPLETED = "restore_completed"
    HEALTH_DEGRADED = "health_degraded"
    WORKER_RECOVERED = "worker_recovered"
    CIRCUIT_BREAKER_OPENED = "circuit_breaker_opened"
    MOBILE_APPROVAL_RECEIVED = "mobile_approval_received"
    REMOTE_COMMAND_RECEIVED = "remote_command_received"


class BrainEvent(BaseModel):
    schema_version: int = 1
    event_id: str = Field(default_factory=lambda: f"evt_{uuid4().hex}")
    task_id: str
    timestamp: datetime = Field(default_factory=utc_now)
    type: EventType
    human_readable_message: str
    structured_payload: dict[str, Any] = Field(default_factory=dict)
