import { validateComposition, type UIComposition } from "./ui-schema";

const generatedAt = "Today · Local mock data";

export const DAILY_STATUS_COMPOSITION = validateComposition({
  schemaVersion: 1,
  id: "daily-status-v0",
  mode: "daily-status",
  label: "Today / Command Briefing",
  summary: "Your day is composed. One approval needs attention; active work is progressing normally.",
  generatedAt,
  objects: [
    {
      id: "today-briefing",
      type: "status-summary",
      title: "Today at a glance",
      eyebrow: "Briefing",
      focus: "Protect the 11:00 focus block. The only immediate decision is the outreach approval.",
      frame: { x: 2, y: 2, width: 28 },
      stats: [
        { label: "Tasks", value: "12" },
        { label: "Active agents", value: "4", tone: "intelligence" },
        { label: "Meetings", value: "2" },
        { label: "Approvals", value: "3", tone: "attention" },
      ],
    },
    {
      id: "outreach-approval",
      type: "approval-action",
      title: "Decision required",
      eyebrow: "Important action",
      tone: "attention",
      request: "Approve Finora outreach batch",
      context: "18 personalized messages are ready. Estimated send window: 14 minutes.",
      actionLabel: "Review approval",
      urgency: "important",
      frame: { x: 3, y: 43, width: 27 },
    },
    {
      id: "coding-agent",
      type: "agent-status",
      title: "Developer agent",
      eyebrow: "Active agent",
      tone: "intelligence",
      agent: "Atlas",
      role: "Coding agent",
      status: "active",
      mission: "Stabilize onboarding and verify the payment hand-off.",
      progress: 68,
      latestAction: "Added recovery coverage for checkout state",
      model: "Codex / GPT-5",
      frame: { x: 72, y: 2, width: 26 },
    },
    {
      id: "growth-chart",
      type: "line-chart",
      title: "Growth signals",
      eyebrow: "Last 7 days",
      tone: "intelligence",
      labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Today"],
      series: [
        { label: "Website visitors", values: [1180, 1260, 1210, 1390, 1510, 1490, 1684] },
        { label: "Instagram growth", values: [820, 910, 960, 1080, 1130, 1210, 1340], color: "#7eaaa1" },
      ],
      frame: { x: 69, y: 37, width: 29 },
    },
    {
      id: "lead-funnel",
      type: "pipeline-funnel",
      title: "Agency funnel",
      eyebrow: "Qualified movement",
      stages: [
        { label: "Prospects", value: 124, detail: "researched" },
        { label: "Qualified", value: 38, detail: "fit confirmed" },
        { label: "Replies", value: 11, detail: "8 positive" },
        { label: "Meetings", value: 4, detail: "booked" },
      ],
      frame: { x: 69, y: 66, width: 29 },
    },
    {
      id: "ai-spend",
      type: "metric",
      title: "AI spend",
      eyebrow: "This month",
      label: "Model usage",
      value: "$84.20",
      delta: "−12% vs plan",
      caption: "Within the $110 guardrail",
      spark: [52, 58, 54, 67, 62, 76, 71, 84],
      frame: { x: 3, y: 70, width: 27 },
    },
    {
      id: "today-timeline",
      type: "timeline",
      title: "Today’s rhythm",
      eyebrow: "Timeline",
      frame: { x: 34, y: 1, width: 32, layer: 2 },
      events: [
        { time: "09:30", title: "Operations review", status: "complete" },
        { time: "11:00", title: "Product focus block", meta: "90 min", status: "active" },
        { time: "15:30", title: "Client call · Finora", status: "upcoming" },
      ],
    },
    {
      id: "verified-result",
      type: "verified-result",
      title: "Latest verified result",
      eyebrow: "Evidence",
      tone: "verified",
      statement: "SaaS signup flow passed all checks",
      evidence: ["14 tests passed", "0 blocking errors", "8 signups today"],
      timestamp: "Verified 08:42",
      frame: { x: 36, y: 74, width: 28, layer: 2 },
    },
  ],
  sequence: [
    { id: "briefing", label: "Briefing", atMs: 500, state: "Thinking", objectIds: ["today-briefing"] },
    { id: "action", label: "Important action", atMs: 1250, state: "Executing", objectIds: ["outreach-approval"] },
    { id: "agent", label: "Active agent", atMs: 2050, state: "Executing", objectIds: ["coding-agent"] },
    { id: "signals", label: "Graph and funnel", atMs: 2900, state: "Thinking", objectIds: ["growth-chart", "lead-funnel", "ai-spend"] },
    { id: "timeline", label: "Timeline", atMs: 3850, state: "Thinking", objectIds: ["today-timeline"] },
    { id: "verified", label: "Verified result", atMs: 4700, state: "Verifying", objectIds: ["verified-result"] },
  ],
});

export const AGENCY_COMPOSITION = validateComposition({
  schemaVersion: 1,
  id: "agency-focus-v0",
  mode: "agency",
  label: "Agency / Live Focus",
  summary: "Agency focus is composed. Qualification is healthy; the prepared outreach batch awaits approval.",
  generatedAt,
  objects: [
    {
      id: "agency-funnel",
      type: "pipeline-funnel",
      title: "Lead funnel",
      eyebrow: "Agency focus",
      tone: "intelligence",
      stages: [
        { label: "Researched", value: 124, detail: "+18 today" },
        { label: "Qualified", value: 38, detail: "31% fit" },
        { label: "Contacted", value: 26, detail: "68% sent" },
        { label: "Replies", value: 11, detail: "8 positive" },
        { label: "Meetings", value: 4, detail: "2 this week" },
      ],
      frame: { x: 2, y: 2, width: 29 },
    },
    {
      id: "agency-approval",
      type: "approval-action",
      title: "Outreach ready",
      eyebrow: "Approval",
      tone: "attention",
      request: "Release 18 personalized messages",
      context: "All leads meet ICP rules. No duplicates or blocked domains detected.",
      actionLabel: "Review batch",
      urgency: "important",
      frame: { x: 3, y: 65, width: 27 },
    },
    {
      id: "sales-agent",
      type: "agent-status",
      title: "Lead research agent",
      eyebrow: "Relevant agent work",
      agent: "Scout",
      role: "Sales intelligence",
      status: "active",
      mission: "Qualify B2B SaaS founders in the UK and UAE.",
      progress: 74,
      latestAction: "Confirmed 9 decision-maker profiles",
      model: "GPT-5 mini",
      frame: { x: 72, y: 2, width: 26 },
    },
    {
      id: "agency-performance",
      type: "line-chart",
      title: "Website / SaaS performance",
      eyebrow: "7-day signal",
      labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Today"],
      series: [
        { label: "Visitors", values: [1180, 1260, 1210, 1390, 1510, 1490, 1684] },
        { label: "Signups ×100", values: [400, 500, 400, 600, 700, 700, 800], color: "#87bda0" },
      ],
      frame: { x: 69, y: 42, width: 29 },
    },
    {
      id: "outreach-flow",
      type: "causal-diagram",
      title: "Outreach movement",
      eyebrow: "Workflow",
      nodes: [
        { id: "research", label: "Research", detail: "124", tone: "neutral" },
        { id: "qualify", label: "Qualify", detail: "38", tone: "intelligence" },
        { id: "personalize", label: "Personalize", detail: "18", tone: "attention" },
        { id: "reply", label: "Replies", detail: "11", tone: "verified" },
      ],
      edges: [
        { from: "research", to: "qualify" },
        { from: "qualify", to: "personalize" },
        { from: "personalize", to: "reply" },
      ],
      frame: { x: 34, y: 1, width: 33, layer: 2 },
    },
    {
      id: "agency-verified",
      type: "verified-result",
      title: "Quality check",
      eyebrow: "Verified",
      tone: "verified",
      statement: "Outbound batch passed preflight",
      evidence: ["18/18 personalized", "0 duplicate leads", "Domains validated"],
      timestamp: "Verified 09:12",
      frame: { x: 36, y: 74, width: 28, layer: 2 },
    },
  ],
  sequence: [
    { id: "briefing", label: "Agency briefing", atMs: 450, state: "Thinking", objectIds: ["agency-funnel"] },
    { id: "action", label: "Approval", atMs: 1200, state: "Executing", objectIds: ["agency-approval"] },
    { id: "agent", label: "Agent", atMs: 1950, state: "Executing", objectIds: ["sales-agent"] },
    { id: "signals", label: "Performance", atMs: 2750, state: "Thinking", objectIds: ["agency-performance", "outreach-flow"] },
    { id: "verified", label: "Verification", atMs: 3700, state: "Verifying", objectIds: ["agency-verified"] },
  ],
});

export const DEVELOPER_COMPOSITION = validateComposition({
  schemaVersion: 1,
  id: "developer-focus-v0",
  mode: "developer",
  label: "Developer / Current Mission",
  summary: "Developer focus is composed. The current mission is progressing and the latest verification is clean.",
  generatedAt,
  objects: [
    {
      id: "dev-mission",
      type: "status-summary",
      title: "Current coding mission",
      eyebrow: "Developer focus",
      focus: "Stabilize onboarding and make the payment hand-off observable before the next release candidate.",
      stats: [
        { label: "Progress", value: "68%", tone: "intelligence" },
        { label: "Files changed", value: "7" },
        { label: "Tests", value: "14/14", tone: "verified" },
        { label: "Blockers", value: "0" },
      ],
      frame: { x: 2, y: 2, width: 29 },
    },
    {
      id: "dev-agent",
      type: "agent-status",
      title: "Coding agent",
      eyebrow: "Active agent",
      tone: "intelligence",
      agent: "Atlas",
      role: "Implementation / review",
      status: "active",
      mission: "Harden checkout recovery and onboarding state.",
      progress: 68,
      latestAction: "Added recovery coverage for checkout state",
      model: "Codex / GPT-5",
      frame: { x: 72, y: 2, width: 26 },
    },
    {
      id: "dev-latest-action",
      type: "timeline",
      title: "Latest actions",
      eyebrow: "Execution trace",
      events: [
        { time: "09:18", title: "Checkout recovery implemented", status: "complete" },
        { time: "09:24", title: "Type and unit checks", meta: "14 passed", status: "complete" },
        { time: "Now", title: "Browser flow verification", status: "active" },
      ],
      frame: { x: 69, y: 47, width: 29 },
    },
    {
      id: "dev-workflow",
      type: "causal-diagram",
      title: "Mission path",
      eyebrow: "Workflow",
      nodes: [
        { id: "inspect", label: "Inspect", tone: "neutral" },
        { id: "implement", label: "Implement", tone: "intelligence" },
        { id: "test", label: "Test", tone: "intelligence" },
        { id: "verify", label: "Verify", tone: "verified" },
      ],
      edges: [
        { from: "inspect", to: "implement" },
        { from: "implement", to: "test" },
        { from: "test", to: "verify" },
      ],
      frame: { x: 34, y: 1, width: 33, layer: 2 },
    },
    {
      id: "dev-model",
      type: "metric",
      title: "Current model",
      eyebrow: "Routing",
      label: "Codex / GPT-5",
      value: "High",
      delta: "Reasoning effort",
      caption: "Selected for repository implementation",
      spark: [35, 42, 38, 56, 61, 64, 68],
      frame: { x: 3, y: 66, width: 27 },
    },
    {
      id: "dev-verified",
      type: "verified-result",
      title: "Verification status",
      eyebrow: "Latest result",
      tone: "verified",
      statement: "Checkout recovery flow is clean",
      evidence: ["14 tests passed", "Typecheck passed", "No console errors"],
      timestamp: "Verified 09:27",
      frame: { x: 36, y: 74, width: 28, layer: 2 },
    },
  ],
  sequence: [
    { id: "mission", label: "Mission", atMs: 450, state: "Thinking", objectIds: ["dev-mission"] },
    { id: "agent", label: "Agent", atMs: 1200, state: "Executing", objectIds: ["dev-agent"] },
    { id: "path", label: "Mission path", atMs: 2050, state: "Thinking", objectIds: ["dev-workflow", "dev-model"] },
    { id: "timeline", label: "Latest actions", atMs: 2900, state: "Executing", objectIds: ["dev-latest-action"] },
    { id: "verified", label: "Verification", atMs: 3800, state: "Verifying", objectIds: ["dev-verified"] },
  ],
});

export const COMPOSITIONS_BY_MODE = {
  "daily-status": DAILY_STATUS_COMPOSITION,
  agency: AGENCY_COMPOSITION,
  developer: DEVELOPER_COMPOSITION,
} satisfies Partial<Record<UIComposition["mode"], UIComposition>>;
